version: '3.8'

services:
  api:
    build: .
    container_name: real-estate-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/real_estate_db
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - real-estate-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - real-estate-network

networks:
  real-estate-network:
    driver: bridge

volumes:
  mongo_data: